// ```
version: '3.8'

services:
  microblog-api:
    build: .
    image: microblog-api
    ports:
      - "${MICROBLOG_API_PORT:-5000}:5000"
    volumes:
      - type: volume
        source: data
        target: /data
      - .:/app
    env_file: .env
    environment:
      - DATABASE_URL=sqlite:////data/db.sqlite
      - FLASK_APP=microblog.py
      - FLASK_ENV=production
    command: ./boot.sh
    restart: always

volumes:
  data:
// ```